This is my personal emacs config. I've tried to make use of (limited)
*Spacemacs*-like keybindings where ever possible. So, the config makes
use of =evil= mode heavily. Some of the common keybindings are 

1. ~SPC f f~ - Open file
2. ~SPC b b~ - Show active buffers
3. ~SPC b d~ - Delete buffer

*Python mode*
1. =, p= - Open python REPL (shell)
2. =, z= - Switch to python REPL
3. =, s b= - Send entire buffer to shell for evaluation 
4. ~M-ENT~ - Send current line to shell for evaluation
5. ~C-ENT~ - Send function to shell for evaluation


*Org mode*
1. ~, e~ - Org export dispatch

I've tried (by best) to make emacs load faster and be un-obtrusive as
much as possible. To that end, I've tried to /not/ load features that
might increase typing lag. 
   
The config is highly evolving, so new packages may be added to it on a
regular basis. Feel free to clone and use the entire repo / pick up
snippets along the way. 

* Installation
Most of the installation setup is borrowed from
[[https://github.com/larstvei/dot-emacs][Lars Tveito]]' config. The config is written is completely in org
mode. To install the config, create an empty =init.el= file inside
your =~/.emacs.d/= folder and paste this. 

#+BEGIN_SRC emacs-lisp
(require 'org)
;; Open the configuration
(find-file (concat user-emacs-directory "init.org"))
;; tangle it
(org-babel-tangle)
;; load it
(load-file (concat user-emacs-directory "init.el"))
;; finally byte-compile it
(byte-compile-file (concat user-emacs-directory "init.el"))
#+END_SRC

This will automatically pick up the configuration from =init.org= and
update the =init.el= file. This needs to be done only once. After that 
every time you update =init.org=, emacs will automatically "tangle"
the change and update the =init.el= file.
